-- ==========================================
-- ABECSA COMPLETE MASTER DATABASE SETUP
-- Version: 1.0 (Idempotent & Safe)
-- Includes: Profiles, Apps, Course Apps, Exams, Storage, and Logs
-- ==========================================

-- 1. HELPERS & FUNCTIONS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. CORE TABLES
-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name text,
  role text,
  email text,
  visible_password text,
  manager_id uuid REFERENCES auth.users(id),
  is_locked boolean DEFAULT false
);

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='is_locked') THEN
        ALTER TABLE public.profiles ADD COLUMN is_locked boolean DEFAULT false;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='profiles' AND column_name='manager_id') THEN
        ALTER TABLE public.profiles ADD COLUMN manager_id uuid REFERENCES auth.users(id);
    END IF;
END $$;

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'marketing_manager', 'customer', 'student_ambassador', 'student'));

-- Apps Table
CREATE TABLE IF NOT EXISTS public.apps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  version text DEFAULT '1.0',
  category text DEFAULT 'General',
  icon_url text,
  apk_url text NOT NULL,
  apk_filename text,
  download_count integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Course Applications Table
CREATE TABLE IF NOT EXISTS public.course_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  course_name text NOT NULL,
  branch text,
  message text,
  status text DEFAULT 'Pending',
  type text DEFAULT 'Course',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='course_applications' AND column_name='type') THEN
        ALTER TABLE public.course_applications ADD COLUMN type text DEFAULT 'Course';
    END IF;
END $$;

-- Other Business Tables
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid REFERENCES auth.users NOT NULL,
  conversation_id uuid,
  content text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.websites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  manager_id uuid REFERENCES auth.users(id),
  name text NOT NULL,
  url text,
  status text DEFAULT 'Pending',
  plan text,
  expiry_date date
);

CREATE TABLE IF NOT EXISTS public.user_assets (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  value text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.user_assets DROP CONSTRAINT IF EXISTS user_assets_type_check;
ALTER TABLE public.user_assets ADD CONSTRAINT user_assets_type_check CHECK (type IN ('License', 'Certificate', 'Image'));

CREATE TABLE IF NOT EXISTS public.visitor_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  image_url TEXT NOT NULL,
  visitor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Exam Tables
CREATE TABLE IF NOT EXISTS public.exams (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  google_form_url text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by uuid REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.exam_attempts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  exam_id uuid REFERENCES public.exams(id) NOT NULL,
  status text CHECK (status IN ('started', 'completed', 'flagged')) DEFAULT 'started',
  violation_reason text,
  started_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  completed_at timestamp with time zone,
  UNIQUE(user_id, exam_id)
);

-- 3. ENABLE RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.apps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_attempts ENABLE ROW LEVEL SECURITY;

-- 4. RLS POLICIES (CLEAN SLATE)
-- We drop all potential policies first to avoid "already exists" errors.

DO $$ 
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN 
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename IN ('profiles', 'apps', 'course_applications', 'messages', 'websites', 'user_assets', 'visitor_logs', 'exams', 'exam_attempts')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', rec.policyname, rec.tablename);
    END LOOP;
END $$;

-- RECREATE POLICIES
-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins manage all profiles" ON profiles FOR ALL USING (is_admin());

-- Apps
CREATE POLICY "Public can read active apps" ON apps FOR SELECT USING (is_active = true);
CREATE POLICY "Admins manage apps" ON apps FOR ALL USING (is_admin());

-- Course Applications
CREATE POLICY "policy_insert_applications" ON course_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "policy_select_applications" ON course_applications FOR SELECT USING (true);
CREATE POLICY "policy_update_applications" ON course_applications FOR UPDATE USING (true);
CREATE POLICY "policy_delete_applications" ON course_applications FOR DELETE USING (true);

-- Messages
CREATE POLICY "Messages viewable by everyone" ON messages FOR SELECT USING (true);
CREATE POLICY "Users can insert messages" ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Admins manage messages" ON messages FOR ALL USING (is_admin());

-- Websites
CREATE POLICY "Users view own websites" ON websites FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Managers view own websites" ON websites FOR SELECT USING (auth.uid() = manager_id);
CREATE POLICY "Admins manage websites" ON websites FOR ALL USING (is_admin());

-- User Assets
CREATE POLICY "Users view own assets" ON user_assets FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins manage assets" ON user_assets FOR ALL USING (is_admin());

-- Visitor Logs
CREATE POLICY "Allow public insert to visitor_logs" ON visitor_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage visitor_logs" ON visitor_logs FOR ALL USING (is_admin() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'marketing_manager'));

-- Exams
CREATE POLICY "Exams viewable by everyone" ON exams FOR SELECT USING (true);
CREATE POLICY "Admins manage exams" ON exams FOR ALL USING (is_admin());

-- Exam Attempts
CREATE POLICY "Users view own attempts" ON exam_attempts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users insert own attempts" ON exam_attempts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins manage attempts" ON exam_attempts FOR ALL USING (is_admin());

-- 5. FUNCTIONS
CREATE OR REPLACE FUNCTION increment_app_download(app_id uuid)
RETURNS void AS $$
  UPDATE apps SET download_count = download_count + 1 WHERE id = app_id;
$$ LANGUAGE sql SECURITY DEFINER;

-- 6. STORAGE BUCKETS
INSERT INTO storage.buckets (id, name, public) VALUES ('public-files', 'public-files', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('visitor-captures', 'visitor-captures', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('apps-files', 'apps-files', true) ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies
DO $$ 
DECLARE
    rec RECORD;
BEGIN
    FOR rec IN SELECT policyname FROM pg_policies WHERE tablename = 'objects' AND schemaname = 'storage' LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON storage.objects', rec.policyname);
    END LOOP;
END $$;

CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING ( bucket_id IN ('public-files', 'visitor-captures', 'apps-files') );
CREATE POLICY "Authenticated Upload Access" ON storage.objects FOR INSERT WITH CHECK ( (bucket_id = 'public-files' OR bucket_id = 'apps-files') AND auth.role() = 'authenticated' );
CREATE POLICY "Public Visitor Capture Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'visitor-captures' );
CREATE POLICY "Admin Delete Objects" ON storage.objects FOR DELETE USING ( is_admin() );
