-- COMPLETE DATABASE SETUP
-- Run this to fix "relation does not exist" errors.
-- It safely creates tables only if they are missing.

-- 1. Create PROFILES (if missing)
create table if not exists profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role text check (role in ('admin', 'marketing_manager', 'customer')),
  email text,
  visible_password text -- Storing password for Admin visibility (Insecure but requested)
);
alter table profiles enable row level security;

-- 2. Create MESSAGES (if missing)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  conversation_id uuid, -- Added directly here
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
alter table messages enable row level security;

-- 3. Create WEBSITES (if missing)
create table if not exists websites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  manager_id uuid references auth.users(id), -- Added directly here
  name text not null,
  url text,
  status text default 'Pending',
  plan text,
  expiry_date date
);
alter table websites enable row level security;

-- 4. Safe Column Additions (for existing tables)
do $$ 
begin
  -- Fix Messages
  if not exists (select 1 from information_schema.columns where table_name='messages' and column_name='conversation_id') then
    alter table messages add column conversation_id uuid;
  end if;

  -- Fix Websites
  if not exists (select 1 from information_schema.columns where table_name='websites' and column_name='manager_id') then
    alter table websites add column manager_id uuid references auth.users(id);
  end if;

  -- Fix Profiles (Add visible_password)
  if not exists (select 1 from information_schema.columns where table_name='profiles' and column_name='visible_password') then
    alter table profiles add column visible_password text;
  end if;
end $$;

-- 5. RELOAD POLICIES (Drop all to be safe, then recreate)
-- Profiles
drop policy if exists "Public profiles are viewable by everyone" on profiles;
drop policy if exists "Users can insert their own profile" on profiles;
drop policy if exists "Users can update their own profile" on profiles;
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on profiles for update using (auth.uid() = id);

-- Messages
drop policy if exists "Messages are viewable by everyone" on messages;
drop policy if exists "Users can insert messages" on messages;
create policy "Messages are viewable by everyone" on messages for select using (true);
create policy "Users can insert messages" on messages for insert with check (auth.uid() = sender_id);

-- Websites
drop policy if exists "Users can view own websites" on websites;
drop policy if exists "Users can insert own websites" on websites;
drop policy if exists "Managers can view sold websites" on websites;
drop policy if exists "Managers can insert websites" on websites;
drop policy if exists "Admins View All" on websites;

create policy "Users can view own websites" on websites for select using (auth.uid() = user_id);
create policy "Users can insert own websites" on websites for insert with check (auth.uid() = user_id);
create policy "Managers can view sold websites" on websites for select using (auth.uid() = manager_id);
create policy "Managers can insert websites" on websites for insert with check (auth.uid() = manager_id);
create policy "Admins View All" on websites for select using (true);

-- 6. ADMIN OVERRIDES (Robust RLS)
-- Function to check if user is admin (Security Definer to avoid recursion)
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Profiles: Admins can do ANYTHING
drop policy if exists "Admins can insert profiles" on profiles;
drop policy if exists "Admins can update profiles" on profiles;
drop policy if exists "Admins can delete profiles" on profiles;
create policy "Admins can insert profiles" on profiles for insert with check (is_admin());
create policy "Admins can update profiles" on profiles for update using (is_admin());
create policy "Admins can delete profiles" on profiles for delete using (is_admin());

-- Websites: Admins can do ANYTHING
drop policy if exists "Admins can insert websites" on websites;
drop policy if exists "Admins can update websites" on websites;
drop policy if exists "Admins can delete websites" on websites;
create policy "Admins can insert websites" on websites for insert with check (is_admin());
create policy "Admins can update websites" on websites for update using (is_admin());
create policy "Admins can delete websites" on websites for delete using (is_admin());

-- Messages: Admins can do ANYTHING
drop policy if exists "Admins can insert messages" on messages;
drop policy if exists "Admins can update messages" on messages;
drop policy if exists "Admins can delete messages" on messages;
create policy "Admins can insert messages" on messages for insert with check (is_admin());
create policy "Admins can update messages" on messages for update using (is_admin());
create policy "Admins can delete messages" on messages for delete using (is_admin());
