-- Consolidated Update: Run this to fix everything

-- 1. Create Websites Table (if it wasn't created before)
create table if not exists websites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  url text,
  status text default 'Pending',
  plan text,
  expiry_date date
);

-- 2. Add conversation_id to messages (if missing)
do $$ 
begin
  if not exists (select 1 from information_schema.columns where table_name='messages' and column_name='conversation_id') then
    alter table messages add column conversation_id uuid;
  end if;
end $$;

-- 3. Add manager_id to websites (if missing)
do $$ 
begin
  if not exists (select 1 from information_schema.columns where table_name='websites' and column_name='manager_id') then
    alter table websites add column manager_id uuid references auth.users(id);
  end if;
end $$;

-- 4. Enable RLS
alter table websites enable row level security;

-- 5. Drop existing policies to avoid conflicts (clean slate for these tables)
drop policy if exists "Users can view own websites" on websites;
drop policy if exists "Users can insert own websites" on websites;
drop policy if exists "Managers can view sold websites" on websites;
drop policy if exists "Managers can insert websites" on websites;
drop policy if exists "Admins View All" on websites;

-- 6. Apply Policies
create policy "Users can view own websites" on websites for select using (auth.uid() = user_id);
create policy "Users can insert own websites" on websites for insert with check (auth.uid() = user_id);

create policy "Managers can view sold websites" on websites for select using (auth.uid() = manager_id);
create policy "Managers can insert websites" on websites for insert with check (auth.uid() = manager_id);

create policy "Admins View All" on websites for select using (true);
