-- ==========================================
-- MASTER ABECSA INTEGRATED SETUP & REPAIR
-- Includes: Core tables, Assets, Exams, Storage, and Visitor Logs
-- ==========================================

-- 1. EXTENSIONS & HELPERS
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. CORE TABLES SETUP
-- Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name text,
  role text,
  email text,
  visible_password text,
  manager_id uuid REFERENCES auth.users(id),
  is_locked boolean DEFAULT false
);

-- Messages
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id uuid REFERENCES auth.users NOT NULL,
  conversation_id uuid,
  content text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- Websites
CREATE TABLE IF NOT EXISTS public.websites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  manager_id uuid REFERENCES auth.users(id),
  name text NOT NULL,
  url text,
  status text DEFAULT 'Pending',
  plan text,
  expiry_date date
);

-- User Assets
CREATE TABLE IF NOT EXISTS public.user_assets (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  value text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Visitor Logs
CREATE TABLE IF NOT EXISTS public.visitor_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  image_url TEXT NOT NULL,
  visitor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  metadata JSONB DEFAULT '{}'::jsonb
);

-- 3. EXAM TABLES
CREATE TABLE IF NOT EXISTS public.exams (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  google_form_url text NOT NULL,
  start_time timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  created_by uuid REFERENCES auth.users(id)
);

CREATE TABLE IF NOT EXISTS public.exam_attempts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) NOT NULL,
  exam_id uuid REFERENCES public.exams(id) NOT NULL,
  status text CHECK (status IN ('started', 'completed', 'flagged')) DEFAULT 'started',
  violation_reason text,
  started_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  completed_at timestamp with time zone,
  UNIQUE(user_id, exam_id)
);

-- 4. CONSTRAINTS & COLUMNS (Idempotent)
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_role_check CHECK (role IN ('admin', 'marketing_manager', 'customer', 'student_ambassador', 'student'));

ALTER TABLE public.user_assets DROP CONSTRAINT IF EXISTS user_assets_type_check;
ALTER TABLE public.user_assets ADD CONSTRAINT user_assets_type_check CHECK (type IN ('License', 'Certificate', 'Image'));

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_locked boolean DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS manager_id uuid REFERENCES auth.users(id);

-- 5. RLS ENABLEMENT
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.websites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.exam_attempts ENABLE ROW LEVEL SECURITY;

-- 6. RLS POLICIES (Full Clean Slate Recreate)

-- Profiles
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
DROP POLICY IF EXISTS "Admins manage all profiles" ON profiles;
CREATE POLICY "Admins manage all profiles" ON profiles FOR ALL USING (is_admin());

-- Messages
DROP POLICY IF EXISTS "Messages viewable by everyone" ON messages;
CREATE POLICY "Messages viewable by everyone" ON messages FOR SELECT USING (true);
DROP POLICY IF EXISTS "Users can insert messages" ON messages;
CREATE POLICY "Users can insert messages" ON messages FOR INSERT WITH CHECK (auth.uid() = sender_id);
DROP POLICY IF EXISTS "Admins manage messages" ON messages;
CREATE POLICY "Admins manage messages" ON messages FOR ALL USING (is_admin());

-- Websites
DROP POLICY IF EXISTS "Users view own websites" ON websites;
CREATE POLICY "Users view own websites" ON websites FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Managers view own websites" ON websites;
CREATE POLICY "Managers view own websites" ON websites FOR SELECT USING (auth.uid() = manager_id);
DROP POLICY IF EXISTS "Admins manage websites" ON websites;
CREATE POLICY "Admins manage websites" ON websites FOR ALL USING (is_admin());

-- User Assets
DROP POLICY IF EXISTS "Users view own assets" ON user_assets;
CREATE POLICY "Users view own assets" ON user_assets FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins manage assets" ON user_assets;
CREATE POLICY "Admins manage assets" ON user_assets FOR ALL USING (is_admin());

-- Visitor Logs
DROP POLICY IF EXISTS "Allow public insert to visitor_logs" ON visitor_logs;
CREATE POLICY "Allow public insert to visitor_logs" ON visitor_logs FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admins manage visitor_logs" ON visitor_logs;
CREATE POLICY "Admins manage visitor_logs" ON visitor_logs FOR ALL USING (is_admin() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('marketing_manager')));

-- Exams
DROP POLICY IF EXISTS "Exams viewable by everyone" ON exams;
CREATE POLICY "Exams viewable by everyone" ON exams FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins manage exams" ON exams;
CREATE POLICY "Admins manage exams" ON exams FOR ALL USING (is_admin());

-- Exam Attempts
DROP POLICY IF EXISTS "Users view own attempts" ON exam_attempts;
CREATE POLICY "Users view own attempts" ON exam_attempts FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users insert own attempts" ON exam_attempts;
CREATE POLICY "Users insert own attempts" ON exam_attempts FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins manage attempts" ON exam_attempts;
CREATE POLICY "Admins manage attempts" ON exam_attempts FOR ALL USING (is_admin());

-- 7. STORAGE BUCKETS & POLICIES
-- Ensure Buckets
INSERT INTO storage.buckets (id, name, public) VALUES ('public-files', 'public-files', true) ON CONFLICT (id) DO UPDATE SET public = true;
INSERT INTO storage.buckets (id, name, public) VALUES ('visitor-captures', 'visitor-captures', true) ON CONFLICT (id) DO UPDATE SET public = true;

-- storage.objects Policies (Clean Slate)
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT USING ( bucket_id IN ('public-files', 'visitor-captures') );

DROP POLICY IF EXISTS "Authenticated Upload Access" ON storage.objects;
CREATE POLICY "Authenticated Upload Access" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'public-files' AND auth.role() = 'authenticated' );

DROP POLICY IF EXISTS "Public Visitor Capture Upload" ON storage.objects;
CREATE POLICY "Public Visitor Capture Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'visitor-captures' );

DROP POLICY IF EXISTS "Admin Delete Captures" ON storage.objects;
CREATE POLICY "Admin Delete Captures" ON storage.objects FOR DELETE USING ( auth.role() = 'authenticated' );
