-- 1. Add conversation_id to messages
alter table messages add column conversation_id uuid;
-- Optional: link to profiles (not strictly necessary but good for integrity)
-- alter table messages add constraint fk_conversation foreign key (conversation_id) references auth.users(id);

-- 2. Create Websites Table
create table websites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  url text,
  status text default 'Pending',
  plan text,
  expiry_date date
);

alter table websites enable row level security;

-- Policies
create policy "Users can view own websites" on websites for select using (auth.uid() = user_id);
create policy "Users can insert own websites" on websites for insert with check (auth.uid() = user_id);
