-- Create Profiles Table (extends Auth)
create table profiles (
  id uuid references auth.users not null primary key,
  full_name text,
  role text check (role in ('admin', 'marketing_manager', 'customer')),
  email text
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;

-- Create Messages Table
create table messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table messages enable row level security;

-- POLICIES (Simple for now: allow all logged in users to read/write)
-- In production, you would want stricter policies.
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update their own profile" on profiles for update using (auth.uid() = id);

create policy "Messages are viewable by everyone" on messages for select using (true);
create policy "Users can insert messages" on messages for insert with check (auth.uid() = sender_id);
