-- Run this query in your Supabase SQL Editor to create the missing table

create table if not exists public.course_applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  course_name text not null,
  branch text,
  message text,
  status text default 'Pending'::text
);

-- Optional: Enable RLS (Row Level Security) if not already enabled
alter table public.course_applications enable row level security;

-- Policy: Allow anyone (anon) to insert applications
create policy "Enable insert for all users" on public.course_applications
  for insert with check (true);

-- Policy: Allow admins/authenticated users to view applications
-- (Adjust this based on your actual auth needs, currently allowing read for all to ensure admin dashboard works smoothly during dev)
create policy "Enable read access for all" on public.course_applications
  for select using (true);

-- Policy: Allow admins to update status
create policy "Enable update for all" on public.course_applications
  for update using (true);

-- Policy: Allow admins to delete
create policy "Enable delete for all" on public.course_applications
  for delete using (true);
